### ISSUE TITLE
创建多个 container 的 pod 报错

### ISSUE THREAD

**Issue by chilianyi** [Project-HAMi/HAMi#212]
创建 pod 报错：

![企业微信截图_17107486711442](https://github.com/Project-HAMi/HAMi/assets/5917832/844a1c35-4b5e-45c5-b849-9ed11c850a99)

hami-scheduler 中 vgpu-scheduler-extender 容器报错：
```
2024-03-18T18:53:37.543856878+08:00 2024/03/18 10:53:37 http2: panic serving 127.0.0.1:49194: runtime error: index out of range [1] with length 1
2024-03-18T18:53:37.543869390+08:00 goroutine 5398 [running]:
2024-03-18T18:53:37.543873665+08:00 net/http.(*http2serverConn).runHandler.func1()
2024-03-18T18:53:37.543876731+08:00  /usr/local/go/src/net/http/h2_bundle.go:6186 +0x13b
2024-03-18T18:53:37.543879026+08:00 panic({0x1902880?, 0xc000ec17b8?})
2024-03-18T18:53:37.543881375+08:00  /usr/local/go/src/runtime/panic.go:914 +0x21f
2024-03-18T18:53:37.543884332+08:00 github.com/Project-HAMi/HAMi/pkg/scheduler.calcScore(0xc00009a2a0, 0xc0016fdc20?, {0xc000e4dc10, 0x2, 0xc0012a081c?}, 0x0?, 0x0?)
2024-03-18T18:53:37.543886755+08:00  /k8s-vgpu/pkg/scheduler/score.go:208 +0xaae
2024-03-18T18:53:37.543889394+08:00 github.com/Project-HAMi/HAMi/pkg/scheduler.(*Scheduler).Filter(0xc000458000, {0xc000d82900?, 0x0?, 0xc0016fdc20?})
2024-03-18T18:53:37.543898751+08:00  /k8s-vgpu/pkg/scheduler/scheduler.go:366 +0x525
2024-03-18T18:53:37.543901385+08:00 github.com/Project-HAMi/HAMi/pkg/scheduler/routes.PredicateRoute.func1({0x1c7d308, 0xc0001282b0}, 0xc000229800, {0x0?, 0x0?, 0x0?})
2024-03-18T18:53:37.543903715+08:00  /k8s-vgpu/pkg/scheduler/routes/route.go:59 +0x33b
2024-03-18T18:53:37.543906167+08:00 github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0012ab0e0, {0x1c7d308, 0xc0001282b0}, 0xc000229800)
2024-03-18T18:53:37.543908807+08:00  /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x7eb
2024-03-18T18:53:37.543911495+08:00 net/http.serverHandler.ServeHTTP({0x18?}, {0x1c7d308?, 0xc0001282b0?}, 0xc0016fa780?)
2024-03-18T18:53:37.543913986+08:00  /usr/local/go/src/net/http/server.go:2938 +0x8e
2024-03-18T18:53:37.543916367+08:00 net/http.initALPNRequest.ServeHTTP({{0x1c8ac90?, 0xc001246f30?}, 0xc001829500?, {0xc000e1c000?}}, {0x1c7d308, 0xc0001282b0}, 0xc000229800)
2024-03-18T18:53:37.543918780+08:00  /usr/local/go/src/net/http/server.go:3546 +0x231
2024-03-18T18:53:37.543921152+08:00 net/http.(*http2serverConn).runHandler(0x299f100?, 0x0?, 0x0?, 0xc001800d20?)
2024-03-18T18:53:37.543923501+08:00  /usr/local/go/src/net/http/h2_bundle.go:6193 +0xbb
2024-03-18T18:53:37.543926253+08:00 created by net/http.(*http2serverConn).scheduleHandler in goroutine 3322
2024-03-18T18:53:37.543928625+08:00  /usr/local/go/src/net/http/h2_bundle.go:6128 +0x21d
```

```
			if sums == 0 {
				for idx := range score.devices {
					score.devices[idx][ctrid] = append(score.devices[idx][ctrid], util.ContainerDevice{})
				}
				continue
			}
```

修改成：

```
			if sums == 0 {
				for idx := range score.devices {
					// add check for nil slice
					if len(score.devices[idx]) <= ctrid {
						// add new slice for the container
						score.devices[idx] = make([]util.ContainerDevices, ctrid+1)
					}
					score.devices[idx][ctrid] = append(score.devices[idx][ctrid], util.ContainerDevice{})
				}
				continue
			}
```

目前不报错了。

**Comment by lengrongfu** [comment]
Can you provide you workload yaml file?

**Comment by chilianyi** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem: 500
          nvidia.com/gpucores: 3
    - name: ubuntu-container1
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]

```

v2.3.9 版本

**Comment by chilianyi** [comment]
试了下 2 个 container，每个 都分配 gpu 的情况，也创建失败。

**Comment by zlianzhuang** [comment]
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod2
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem: 500
          nvidia.com/gpucores: 3
    - name: ubuntu-container1
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem: 500
          nvidia.com/gpucores: 3
两个container时，第二个container是否使用gpu，会有不同的报错

**Comment by zlianzhuang** [comment]
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: gpu-pod
> spec:
>   containers:
>     - name: ubuntu-container
>       image: ubuntu:18.04
>       command: ["bash", "-c", "sleep 86400"]
>       resources:
>         limits:
>           nvidia.com/gpu: 1
>           nvidia.com/gpumem: 500
>           nvidia.com/gpucores: 3
>     - name: ubuntu-container1
>       image: ubuntu:18.04
>       command: ["bash", "-c", "sleep 86400"]
> ```
> 
> v2.3.9 版本

gpu-pod1   1/2     CrashLoopBackOff

root@SHOULDBEREPLACED:~# kubectl logs gpu-pod1 -c ubuntu-container
bash: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by lengrongfu** [comment]
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: gpu-pod2
> spec:
>   containers:
>     - name: ubuntu-container
>       image: ubuntu:18.04
>       command: ["bash", "-c", "sleep 86400"]
>       resources:
>         limits:
>           nvidia.com/gpu: 1
>           nvidia.com/gpumem: 500
>           nvidia.com/gpucores: 3
>     - name: ubuntu-container1
>       image: ubuntu:18.04
>       command: ["bash", "-c", "sleep 86400"]
>       resources:
>         limits:
>           nvidia.com/gpu: 1
>           nvidia.com/gpumem: 500
>           nvidia.com/gpucores: 3
> ```
> 
> gpu-pod2 0/2 ContainerStatusUnknown Pod Allocate failed due to rpc error: code = Unknown desc = no binding pod found on node i-53ghrwb6, which is unexpected 两个container时均申请gpu

look this is a new bug, we can fix it.

**Comment by lengrongfu** [comment]
@chilianyi Can you use the dev image tag to test whether there is an issue?

**Comment by chilianyi** [comment]
Thanks, it is ok now.
