### ISSUE TITLE
INTERNAL ASSERT FAILED in PyTorch during F.conv2d execution

### ISSUE THREAD

**Issue by Curt-Park** [Project-HAMi/HAMi#406]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
With HAMI activated, [the torch model inference](https://github.com/LykosAI/ComfyUI-Inference-Core-Nodes/blob/main/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/leres/leres/Resnext_torch.py#L199) causes `INTERNAL ASSERT FAILED`.

As I see the logs, HAMI returns `free` and `limit` properly, so I suspect `pytorch_used_bytes[device]` may return a large value.
Could you provide anything to try please?

Related:
- HAMI: https://github.com/Project-HAMi/HAMi-core/blob/main/src/cuda/memory.c#L511
- PyTorch: https://github.com/pytorch/pytorch/blob/main/c10/cuda/CUDAMallocAsyncAllocator.cpp#L535-L539

```bash
  | 2024-07-30 11:18:12 | (no unique labels) |  
  | 2024-07-30 11:18:12 | (no unique labels) | RuntimeError: free_upper_bound + pytorch_used_bytes[device] <= device_total INTERNAL ASSERT FAILED at "../c10/cuda/CUDAMallocAsyncAllocator.cpp":539, please report a bug to PyTorch.
  | 2024-07-30 11:18:12 | (no unique labels) | return F.conv2d(input, weight, bias, self.stride,
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
  | 2024-07-30 11:18:12 | (no unique labels) | return self._conv_forward(input, self.weight, self.bias)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
  | 2024-07-30 11:18:12 | (no unique labels) | return forward_call(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | return self._call_impl(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | x = self.conv1(x)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/leres/leres/Resnext_torch.py", line 199, in _forward_impl
  | 2024-07-30 11:18:12 | (no unique labels) | return self._forward_impl(x)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/leres/leres/Resnext_torch.py", line 223, in forward
  | 2024-07-30 11:18:12 | (no unique labels) | return forward_call(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | return self._call_impl(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | x = self.encoder(x) # 1/32, 1/16, 1/8, 1/4
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/leres/leres/network_auxi.py", line 96, in forward
  | 2024-07-30 11:18:12 | (no unique labels) | return forward_call(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | return self._call_impl(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | lateral_out = self.encoder_modules(x)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/leres/leres/multi_depth_model_woauxi.py", line 33, in forward
  | 2024-07-30 11:18:12 | (no unique labels) | return forward_call(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | return self._call_impl(*args, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  | 2024-07-30 11:18:12 | (no unique labels) | prediction = model.depth_model(img_torch)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/leres/leres/depthmap.py", line 45, in estimateleres
  | 2024-07-30 11:18:12 | (no unique labels) | depth = estimateleres(detected_map, self.model, detected_map.shape[1], detected_map.shape[0])
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/leres/__init__.py", line 56, in __call__
  | 2024-07-30 11:18:12 | (no unique labels) | np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 67, in common_annotator_call
  | 2024-07-30 11:18:12 | (no unique labels) | out = common_annotator_call(model, image, resolution=resolution, thr_a=rm_nearest, thr_b=rm_background, boost=kwargs["boost"] == "enable")
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/leres.py", line 22, in execute
  | 2024-07-30 11:18:12 | (no unique labels) | results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
  | 2024-07-30 11:18:12 | (no unique labels) | return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/execution.py", line 81, in get_output_data
  | 2024-07-30 11:18:12 | (no unique labels) | output_data, output_ui = get_output_data(obj, input_data_all)
  | 2024-07-30 11:18:12 | (no unique labels) | File "/home1/workspace/ComfyUI/execution.py", line 151, in recursive_execute
  | 2024-07-30 11:18:12 | (no unique labels) | Traceback (most recent call last):
  | 2024-07-30 11:18:12 | (no unique labels) | !!! Exception during processing !!!
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:39)]: Hijacking cuCtxGetDevice
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:11)]: Hijacking cuDevicePrimaryCtxGetState
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:10)]: into cuDevicePrimaryCtxGetState dev=0
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:39)]: Hijacking cuCtxGetDevice
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:11)]: Hijacking cuDevicePrimaryCtxGetState
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:10)]: into cuDevicePrimaryCtxGetState dev=0
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:39)]: Hijacking cuCtxGetDevice
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:39)]: Hijacking cuCtxGetDevice
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:11)]: Hijacking cuDevicePrimaryCtxGetState
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:10)]: into cuDevicePrimaryCtxGetState dev=0
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:39)]: Hijacking cuCtxGetDevice
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:11)]: Hijacking cuDevicePrimaryCtxGetState
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:context.c:10)]: into cuDevicePrimaryCtxGetState dev=0
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Msg(9:140468614641344:memory.c:511)]: orig free=82547703808 total=84987740160 limit=85899345920 usage=778766080
  | 2024-07-30 11:18:12 | (no unique labels) | [HAMI-core Debug(9:140468614641344:memory.c:510)]: Hijacking cuMemGetInfo_v2
```

### 2. Steps to reproduce the issue

- [ComfyUI](https://github.com/comfyanonymous/ComfyUI) setup with [ComfyUI-Inference-Core-Nodes](https://github.com/LykosAI/ComfyUI-Inference-Core-Nodes) and [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux)
- execute the workflow [hami_error.json](https://github.com/user-attachments/files/16421347/hami_error.json)

#### nvidia-smi
```bash
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          On  | 00000000:1D:00.0 Off |                  Off |
| N/A   55C    P0              77W / 300W |    741MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

Common error checking:
- [ ] The output of `nvidia-smi -a` on your host
- [ ] Your docker or containerd configuration file (e.g: `/etc/docker/daemon.json`)
- [ ] The vgpu-device-plugin container logs
- [ ] The vgpu-scheduler container logs
- [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
- [ ] Docker version from `docker version`
- [ ] Docker command, image and tag used
- [ ] Kernel version from `uname -a`
- [ ] Any relevant kernel output lines from `dmesg`

**Comment by Curt-Park** [comment]
with `PYTORCH_CUDA_ALLOC_CONF=backend:cudaMallocAsync` settings, HAMi cannot estimate the memory usages exactly.

`get_current_device_memory_usage` function returns smaller values than the actual usages, and it makes PyTorch raise `TORCH_INTERNAL_ASSERT`

- https://github.com/Project-HAMi/HAMi-core/blob/main/src/multiprocess/multiprocess_memory_limit.c#L827
- https://github.com/pytorch/pytorch/blob/main/c10/cuda/CUDAMallocAsyncAllocator.cpp#L535-L539

**Comment by Curt-Park** [comment]
related issue
https://github.com/Project-HAMi/HAMi/issues/409

**Comment by chaunceyjiang** [comment]
Thank you for your feedback, I will try to reproduce this issue. It seems to be related to `cudaMallocAsync`.
