### ISSUE TITLE
显存申请异常

### ISSUE THREAD

**Issue by gsakun** [Project-HAMi/HAMi#67]
# 问题描述
相同的任务使用原生的nvidia-device-plugin与4paradigm的deivce-plugin的对比

## 原生
<img width="435" alt="6feed66bb0f65f1802f552e3141ab4a" src="https://github.com/4paradigm/k8s-vgpu-scheduler/assets/24608247/f4eebbc2-c1b5-4769-849b-2cc6d04d9f3d">

![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/24608247/c446a7f1-593e-4902-8e77-3a02c27e80e5)

8G显存最多使用7G+，任务可以正常运行结束

## 4paradigm
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/24608247/1b91f82e-8cf0-477e-8353-919f43ae23da)
显存吃到这个位置就异常了
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/24608247/a7c90954-4111-442b-a362-52cefdece9a7)
```
export CUDA_LAUNCH_BLOCKING=1
```
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/24608247/4f932347-ce38-43fd-9946-878952537a7f)

# 错误日志
```
Loading model...
Processing '20230406155830.jpg'...
[4pdvGPU ERROR (pid:310 thread=140540260047872 allocator.c:53)]: Device 0 OOM 10852066933 / 10307502080
Traceback (most recent call last):
  File "scripts/amg.py", line 239, in <module>
    main(args)
  File "scripts/amg.py", line 222, in main
    masks = generator.generate(image)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 163, in generate
    mask_data = self._generate_masks(image)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 206, in _generate_masks
    crop_data = self._process_crop(image, crop_box, layer_idx, orig_size)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 245, in _process_crop
    batch_data = self._process_batch(points, cropped_im_size, crop_box, orig_size)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 297, in _process_batch
    data.filter(keep_mask)
  File "/demo/segment-anything/segment_anything/utils/amg.py", line 49, in filter
    self._stats[k] = v[torch.as_tensor(keep, device=v.device)]
RuntimeError: CUDA error: unrecognized error code
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
```
Loading model...
Processing '20230406155830.jpg'...
[4pdvGPU ERROR (pid:347 thread=140052197080064 allocator.c:119)]: cuMemoryAllocate failed res=2
[4pdvGPU ERROR (pid:347 thread=140052197080064 allocator.c:53)]: Device 0 OOM 9514732733 / 8589934592
Traceback (most recent call last):
  File "scripts/amg.py", line 239, in <module>
    main(args)
  File "scripts/amg.py", line 222, in main
    masks = generator.generate(image)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 163, in generate
    mask_data = self._generate_masks(image)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 206, in _generate_masks
    crop_data = self._process_crop(image, crop_box, layer_idx, orig_size)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 245, in _process_crop
    batch_data = self._process_batch(points, cropped_im_size, crop_box, orig_size)
  File "/demo/segment-anything/segment_anything/automatic_mask_generator.py", line 297, in _process_batch
    data.filter(keep_mask)
  File "/demo/segment-anything/segment_anything/utils/amg.py", line 49, in filter
    self._stats[k] = v[torch.as_tensor(keep, device=v.device)]
RuntimeError: CUDA error: unrecognized error code
```
错误与 #43 类似
# 测试环境信息
centos 7.9
GPU GeForce RTX 3070
k8s 1.23.4
containerd v1.6.8
device-plugin 4pdosc/k8s-vdevice:v2.2.14
## device-plugin 启动命令
```
         command:
            - nvidia-device-plugin
            - --resource-name=nvidia.com/gpu
            - --mig-strategy=none
            - --device-memory-scaling=1
            - --device-split-count=10
            - --disable-core-limit=true
            - -v=8
```

**Comment by archlitchi** [comment]
这种情况如果是任务自动重启后出现的话，可能升级到2.2.14

**Comment by gsakun** [comment]
> 这种情况如果是任务自动重启后出现的话，可能升级到2.2.14

我这个是手动起了一个sleep的容器，exec进去执行python程序触发的。我的版本就是2.2.14

**Comment by fangfenghuang** [comment]
我也遇到了相同的问题
```bash
CUDA error: unrecognized error code
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
INFO:     10.192.175.97:58342 - "POST /asr_predict HTTP/1.1" 200 OK
[4pdvGPU ERROR (pid:1 thread=139727664858880 allocator.c:53)]: Device 0 OOM 8344567528 / 8053063680
2023-08-31 09:46:50,176 - INFO - asr.py:248 - predict() - CUDA error: unrecognized error code
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by fangfenghuang** [comment]
> 我也遇到了相同的问题，并且环境变量设置了“ACTIVE_OOM_KILLER=0" #43
> 
> ```shell
> CUDA error: unrecognized error code
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> INFO:     10.192.175.97:58342 - "POST /asr_predict HTTP/1.1" 200 OK
> [4pdvGPU ERROR (pid:1 thread=139727664858880 allocator.c:53)]: Device 0 OOM 8344567528 / 8053063680
> 2023-08-31 09:46:50,176 - INFO - asr.py:248 - predict() - CUDA error: unrecognized error code
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> ```

我这边没有问题了，我把batchsize设小一点就没有这个报错了，之前没有修改所有的batchsize，导致这个问题会偶现
