### ISSUE TITLE
分配多个vGPU，实际上就只是用了一个，导致说内存不足

### ISSUE THREAD

**Issue by yuanssai** [Project-HAMi/HAMi#722]
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen2-5-72b
  namespace: default
  labels:
    app: vllm-qwen2-5-72b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-qwen2-5-72b
  template:
    metadata:
      labels:
        app: vllm-qwen2-5-72b
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: pvc-huggingface
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "20Gi"
      containers:
      - name: vllm-qwen2-5-72b
        image: vllm/vllm-openai:latest
        command: ["vllm", "serve", "Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4"]
        args: ["--trust-remote-code"]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token-secret
              key: token
        - name: HF_HUB_ENABLE_HF_TRANSFER
          value: "0"
        - name: LIBCUDA_LOG_LEVEL
          value: "0"
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 4
            nvidia.com/gpumem-percentage: 100
            nvidia.com/gpucores: 100
            nvidia.com/priority: 0
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
EOF
```

```
❯ k logs -f vllm-qwen2-5-72b-6bfc8f48b7-62rgg
[HAMI-core ERROR (pid:1 thread=140669179651136 multiprocess_memory_limit.c:748)]: The current version number 1.1 is different from the file's version number 0.0
[HAMI-core ERROR (pid:1 thread=140669179651136 multiprocess_memory_limit.c:758)]: Limit inconsistency detected for 1th device, 25769803776 expected, get 0
[HAMI-core ERROR (pid:1 thread=140669179651136 multiprocess_memory_limit.c:758)]: Limit inconsistency detected for 15th device, 0 expected, get 100
INFO 12-22 02:13:46 api_server.py:651] vLLM API server version 0.6.5
INFO 12-22 02:13:46 api_server.py:652] args: Namespace(subparser='serve', model_tag='Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4', config='', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='xgrammar', logits_processor_pattern=None, distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, mm_cache_preprocessor=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x7fee94685120>)
INFO 12-22 02:13:46 api_server.py:199] Started engine process with PID 77
[HAMI-core ERROR (pid:77 thread=140519242266432 multiprocess_memory_limit.c:748)]: The current version number 1.1 is different from the file's version number 0.0
[HAMI-core ERROR (pid:77 thread=140519242266432 multiprocess_memory_limit.c:758)]: Limit inconsistency detected for 1th device, 25769803776 expected, get 0
[HAMI-core ERROR (pid:77 thread=140519242266432 multiprocess_memory_limit.c:758)]: Limit inconsistency detected for 15th device, 0 expected, get 100
INFO 12-22 02:13:57 config.py:478] This model supports multiple tasks: {'classify', 'generate', 'embed', 'score', 'reward'}. Defaulting to 'generate'.
INFO 12-22 02:13:58 gptq_marlin.py:109] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
INFO 12-22 02:13:58 config.py:478] This model supports multiple tasks: {'score', 'classify', 'reward', 'generate', 'embed'}. Defaulting to 'generate'.
INFO 12-22 02:13:59 gptq_marlin.py:109] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
INFO 12-22 02:13:59 llm_engine.py:249] Initializing an LLM engine (v0.6.5) with config: model='Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4', speculative_config=None, tokenizer='Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq_marlin, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, mm_cache_preprocessor=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"candidate_compile_sizes":[],"compile_sizes":[],"capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True,
INFO 12-22 02:14:00 selector.py:120] Using Flash Attention backend.
INFO 12-22 02:14:02 model_runner.py:1092] Starting to load model Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4...
INFO 12-22 02:14:02 gptq_marlin.py:200] Using MarlinLinearKernel for GPTQMarlinLinearMethod
[HAMI-core ERROR (pid:77 thread=140519242266432 allocator.c:119)]: cuMemoryAllocate failed res=2
[HAMI-core ERROR (pid:77 thread=140519242266432 allocator.c:119)]: cuMemoryAllocate failed res=2
ERROR 12-22 02:14:02 engine.py:366] CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 514.00 MiB is free. Process 2106 has 23.54 GiB memory in use. Of the allocated memory 23.23 GiB is allocated by PyTorch, and 19.15 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR 12-22 02:14:02 engine.py:366] Traceback (most recent call last):
Process SpawnProcess-1:
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 12-22 02:14:02 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 12-22 02:14:02 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 12-22 02:14:02 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 12-22 02:14:02 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-22 02:14:02 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 288, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 12-22 02:14:02 engine.py:366]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self._init_executor()
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/gpu_executor.py", line 35, in _init_executor
ERROR 12-22 02:14:02 engine.py:366]     self.driver_worker.load_model()
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 155, in load_model
ERROR 12-22 02:14:02 engine.py:366]     self.model_runner.load_model()
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1094, in load_model
ERROR 12-22 02:14:02 engine.py:366]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 12-22 02:14:02 engine.py:366]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
ERROR 12-22 02:14:02 engine.py:366]     return loader.load_model(vllm_config=vllm_config)
ERROR 12-22 02:14:02 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 361, in load_model
ERROR 12-22 02:14:02 engine.py:366]     model = _initialize_model(vllm_config=vllm_config)
ERROR 12-22 02:14:02 engine.py:366]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 114, in _initialize_model
ERROR 12-22 02:14:02 engine.py:366]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 12-22 02:14:02 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 444, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self.model = Qwen2Model(vllm_config=vllm_config,
ERROR 12-22 02:14:02 engine.py:366]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py", line 147, in __init__
ERROR 12-22 02:14:02 engine.py:366]     old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 299, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self.start_layer, self.end_layer, self.layers = make_layers(
ERROR 12-22 02:14:02 engine.py:366]                                                     ^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 551, in make_layers
ERROR 12-22 02:14:02 engine.py:366]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
ERROR 12-22 02:14:02 engine.py:366]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 301, in <lambda>
ERROR 12-22 02:14:02 engine.py:366]     lambda prefix: Qwen2DecoderLayer(config=config,
ERROR 12-22 02:14:02 engine.py:366]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 200, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self.self_attn = Qwen2Attention(
ERROR 12-22 02:14:02 engine.py:366]                      ^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 133, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self.qkv_proj = QKVParallelLinear(
ERROR 12-22 02:14:02 engine.py:366]                     ^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 696, in __init__
ERROR 12-22 02:14:02 engine.py:366]     super().__init__(input_size=input_size,
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 306, in __init__
ERROR 12-22 02:14:02 engine.py:366]     self.quant_method.create_weights(
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/gptq_marlin.py", line 226, in create_weights
ERROR 12-22 02:14:02 engine.py:366]     data=torch.empty(
ERROR 12-22 02:14:02 engine.py:366]          ^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 106, in __torch_function__
ERROR 12-22 02:14:02 engine.py:366]     return func(*args, **kwargs)
ERROR 12-22 02:14:02 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 12-22 02:14:02 engine.py:366] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 514.00 MiB is free. Process 2106 has 23.54 GiB memory in use. Of the allocated memory 23.23 GiB is allocated by PyTorch, and 19.15 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine
    raise e
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
    return cls(ipc_path=ipc_path,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
    self.engine = LLMEngine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 288, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/gpu_executor.py", line 35, in _init_executor
    self.driver_worker.load_model()
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 155, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1094, in load_model
    self.model = get_model(vllm_config=self.vllm_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
    return loader.load_model(vllm_config=vllm_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 361, in load_model
    model = _initialize_model(vllm_config=vllm_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 114, in _initialize_model
    return model_class(vllm_config=vllm_config, prefix=prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 444, in __init__
    self.model = Qwen2Model(vllm_config=vllm_config,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py", line 147, in __init__
    old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 299, in __init__
    self.start_layer, self.end_layer, self.layers = make_layers(
                                                    ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 551, in make_layers
    maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 301, in <lambda>
    lambda prefix: Qwen2DecoderLayer(config=config,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 200, in __init__
    self.self_attn = Qwen2Attention(
                     ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 133, in __init__
    self.qkv_proj = QKVParallelLinear(
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 696, in __init__
    super().__init__(input_size=input_size,
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 306, in __init__
    self.quant_method.create_weights(
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/gptq_marlin.py", line 226, in create_weights
    data=torch.empty(
         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 106, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 514.00 MiB is free. Process 2106 has 23.54 GiB memory in use. Of the allocated memory 23.23 GiB is allocated by PyTorch, and 19.15 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W1222 02:14:03.684255290 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Traceback (most recent call last):
  File "/usr/local/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 201, in main
    args.dispatch_function(args)
  File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 42, in serve
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 675, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 118, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 223, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
```
我查看资源是足够的
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/fdd72648-8ac1-4dd2-a58e-e084dadaf003" />

**Comment by yuanssai** [comment]
我找到问题了，我用的vllm，需要制定参数
--tensor-parallel-size=2就好了
